### ISSUE TITLE
Not supplying format type throws EPIPE

### ISSUE THREAD

**Issue by mhart** [isaacs/tap-mocha-reporter#1]
The README states that you can pipe to `tap-mocha-reporter` without specifying an argument, but this displays usage and throws EPIPE for me.

I'm using the same files as `coverage-example` from tap to test this.

Without an argument to `tap-mocha-reporter`:
```console
$ ./node_modules/.bin/tap test/*.js | ./node_modules/.bin/tap-mocha-reporter
Usage:
  tap-mocha-reporter <type>

Reads TAP data on stdin, and formats to stdout using the specified
reporter.  (Note that some reporters write to files instead of stdout.)

Available format types:

classic doc dot dump html htmlcov json
jsoncov jsonstream landing list markdown
min nyan progress silent spec tap xunit

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:905:11)
    at Object.afterWrite (net.js:721:19)
```
And as soon as I supply an argument, it works:
```console
$ ./node_modules/.bin/tap test/*.js | ./node_modules/.bin/tap-mocha-reporter classic
total ................................................. 14/14
total ................................................. 4/4

  4 passing (188ms)

  ok
```

**Comment by mhart** [comment]
FWIW, supplying `spec` seems to half work:

```console
$ ./node_modules/.bin/tap test/*.js | ./node_modules/.bin/tap-mocha-reporter spec

  ✓ test/bar.test.js ..................................... 4/4
  ✓ test/baz.test.js ..................................... 6/6
total ................................................. 14/14
  ✓ test/foo.test.js ..................................... 4/4
  ✓ undefined

  4 passing (201ms)
  1) missing plan
```
(that last line is in red – signalling an error of some sort?)

**Comment by mhart** [comment]
What's the status of this? Should I close it?

**Comment by isaacs** [comment]
Reporter working as expected, but node-tap's bin should not be throwing EPIPEs.  Better to just exit.
